insert into public.country (id, name)
values  (1, 'Armenia'),
        (2, 'Iraq'),
        (3, 'Georgia'),
        (4, 'Mexico'),
        (5, 'Belize'),
        (6, 'Aruba'),
        (7, 'Bhutan'),
        (8, 'Denmark'),
        (9, 'Mongolia'),
        (10, 'Monaco'),
        (11, 'Haiti'),
        (12, 'Ireland'),
        (13, 'Mali'),
        (14, 'Congo'),
        (15, 'Guam'),
        (16, 'Angola'),
        (17, 'Cuba'),
        (18, 'Laos'),
        (19, 'Libya'),
        (20, 'Ghana'),
        (21, 'Gambia'),
        (22, 'Belgium'),
        (23, 'Benin'),
        (24, 'Djibouti'),
        (25, 'Cyprus'),
        (26, 'Moldova'),
        (27, 'Latvia'),
        (28, 'Italy'),
        (29, 'China'),
        (30, 'Zambia'),
        (31, 'Guinea'),
        (32, 'Macau'),
        (33, 'India'),
        (34, 'Kenya'),
        (35, 'Malawi'),
        (36, 'Guyana'),
        (37, 'Yemen'),
        (38, 'Qatar'),
        (39, 'Malaysia'),
        (40, 'Comoros'),
        (41, 'Mauritius'),
        (42, 'Myanmar'),
        (43, 'Germany'),
        (44, 'Nauru'),
        (45, 'Nepal'),
        (46, 'Vatican'),
        (47, 'Uganda'),
        (48, 'Estonia'),
        (49, 'Singapore'),
        (50, 'Jamaica'),
        (51, 'Niger'),
        (52, 'Russia'),
        (53, 'Nicaragua'),
        (54, 'Ethiopia'),
        (55, 'Serbia'),
        (56, 'Gabon'),
        (57, 'Turkey'),
        (58, 'Sudan'),
        (59, 'Bahamas'),
        (60, 'Niue'),
        (61, 'Togo'),
        (62, 'Croatia'),
        (63, 'Bahrain'),
        (64, 'Thailand'),
        (65, 'Somalia'),
        (66, 'Palau'),
        (67, 'Tokelau'),
        (68, 'France'),
        (69, 'Finland'),
        (70, 'Israel'),
        (71, 'Sri Lanka'),
        (72, 'Samoa'),
        (73, 'Senegal'),
        (74, 'Swaziland'),
        (75, 'Bermuda'),
        (76, 'Slovenia'),
        (77, 'Taiwan'),
        (78, 'Chile'),
        (79, 'USA'),
        (80, 'Fiji'),
        (81, 'Tuvalu'),
        (82, 'Norway'),
        (83, 'Rwanda'),
        (84, 'Chad'),
        (85, 'Isle of Man'),
        (86, 'Oman'),
        (87, 'Panama'),
        (88, 'Peru'),
        (89, 'Réunion'),
        (90, 'Ecuador'),
        (91, 'Kyrgyzstan'),
        (92, 'Iran'),
        (93, 'Seychelles'),
        (94, 'Morocco'),
        (95, 'Cape Verde'),
        (96, 'Dominica'),
        (97, 'Cayman Islands'),
        (98, 'Zimbabwe'),
        (99, 'Saudi Arabia'),
        (100, 'Grenada'),
        (101, 'Montserrat'),
        (102, 'Malta'),
        (103, 'Tajikistan'),
        (104, 'Uruguay'),
        (105, 'Kazakhstan'),
        (106, 'Tunisia'),
        (107, 'Canada'),
        (108, 'East Timor'),
        (109, 'Anguilla'),
        (110, 'Tonga'),
        (111, 'Indonesia'),
        (112, 'Sint Maarten'),
        (113, 'Mozambique'),
        (114, 'Bulgaria'),
        (115, 'Jordan'),
        (116, 'Greece'),
        (117, 'Liberia'),
        (118, 'Slovakia'),
        (119, 'Costa Rica'),
        (120, 'Romania'),
        (121, 'Namibia'),
        (122, 'Lesotho'),
        (123, 'Macedonia'),
        (124, 'Hong Kong'),
        (125, 'Lebanon'),
        (126, 'Nigeria'),
        (127, 'Tanzania'),
        (128, 'Trinidad and Tobago'),
        (129, 'Guatemala'),
        (130, 'Pakistan'),
        (131, 'Côte d`Ivoire'),
        (132, 'Japan'),
        (133, 'Azerbaijan'),
        (134, 'Gibraltar'),
        (135, 'Western Sahara'),
        (136, 'Martinique'),
        (137, 'Uzbekistan'),
        (138, 'Hungary'),
        (139, 'Luxembourg'),
        (140, 'Philippines'),
        (141, 'Brazil'),
        (142, 'Spain'),
        (143, 'Wallis and Futuna'),
        (144, 'Austria'),
        (145, 'Mauritania'),
        (146, 'Afghanistan'),
        (147, 'Lithuania'),
        (148, 'Belarus'),
        (149, 'Switzerland'),
        (150, 'New Caledonia'),
        (151, 'Curaçao'),
        (152, 'Faroe Islands'),
        (153, 'Turkmenistan'),
        (154, 'Bolivia'),
        (155, 'Papua New Guinea'),
        (156, 'Solomon Islands'),
        (157, 'United Kingdom'),
        (158, 'Madagascar'),
        (159, 'Equatorial Guinea'),
        (160, 'Cameroon'),
        (161, 'Brunei Darussalam'),
        (162, 'Ukraine'),
        (163, 'Montenegro'),
        (164, 'Sierra Leone'),
        (165, 'El Salvador'),
        (166, 'New Zealand'),
        (167, 'Syria'),
        (168, 'French Guiana'),
        (169, 'Australia'),
        (170, 'Andorra'),
        (171, 'Venezuela'),
        (172, 'United Arab Emirates'),
        (173, 'San Marino'),
        (174, 'Guinea-Bissau'),
        (175, 'Bangladesh'),
        (176, 'Botswana'),
        (177, 'Albania'),
        (178, 'Greenland'),
        (179, 'South Sudan'),
        (180, 'North Korea'),
        (181, 'Norfolk Island'),
        (182, 'US Virgin Islands'),
        (183, 'Honduras'),
        (184, 'Dominican Republic'),
        (185, 'Guadeloupe'),
        (186, 'Kuwait'),
        (187, 'Central African Republic'),
        (188, 'Northern Mariana Islands'),
        (189, 'Czech Republic'),
        (190, 'Netherlands'),
        (191, 'British Virgin Islands'),
        (192, 'São Tomé and Príncipe'),
        (193, 'Burundi'),
        (194, 'Suriname'),
        (195, 'Cook Islands'),
        (196, 'Saint Helena'),
        (197, 'Saint Kitts and Nevis'),
        (198, 'Falkland Islands'),
        (199, 'Vanuatu'),
        (200, 'South Korea'),
        (201, 'South Africa'),
        (202, 'Vietnam'),
        (203, 'Congo, Democratic Republic'),
        (204, 'Egypt'),
        (205, 'Kiribati'),
        (206, 'Puerto Rico'),
        (207, 'Eritrea'),
        (208, 'French Polynesia'),
        (209, 'Turks and Caicos Islands'),
        (210, 'Paraguay'),
        (211, 'Poland'),
        (212, 'Saint Vincent and the Grenadines'),
        (213, 'Palestine'),
        (214, 'Svalbard and Jan Mayen'),
        (215, 'Algeria'),
        (216, 'Barbados'),
        (217, 'Burkina Faso'),
        (218, 'Colombia'),
        (219, 'Iceland'),
        (220, 'Maldives'),
        (221, 'Marshall Islands'),
        (222, 'Micronesia'),
        (223, 'Pitcairn Islands'),
        (224, 'Saint Pierre and Miquelon'),
        (225, 'Sweden'),
        (226, 'American Samoa'),
        (227, 'Antigua and Barbuda'),
        (228, 'Argentina'),
        (229, 'Cambodia'),
        (230, 'Bonaire, Sint Eustatius and Saba'),
        (231, 'Portugal'),
        (232, 'Saint Lucia'),
        (233, 'Bosnia and Herzegovina'),
        (234, 'Liechtenstein'),
        (235, 'UK'),
        (236, 'Soviet Union'),
        (237, 'Czechoslovakia'),
        (238, 'Isle Of Man'),
        (239, 'West Germany'),
        (240, 'Yugoslavia'),
        (241, 'East Germany'),
        (242, 'Côte d''Ivoire'),
        (243, 'Netherlands Antilles'),
        (244, 'Zaire'),
        (245, 'Federal Republic of Yugoslavia'),
        (246, 'Republic of North Macedonia'),
        (247, 'Svalbard And Jan Mayen'),
        (248, 'The Democratic Republic Of Congo'),
        (249, 'North Vietnam'),
        (250, 'Serbia and Montenegro'),
        (251, 'Kosovo'),
        (252, 'Macao'),
        (253, 'Reunion'),
        (254, 'Korea'),
        (255, 'Brunei'),
        (256, 'Burma'),
        (257, 'Holy See (Vatican City State)');
