insert into language (name)
values  ('English'),
        ('Italian'),
        ('German'),
        ('Danish'),
        ('French'),
        ('Hungarian'),
        ('Russian'),
        ('Spanish'),
        ('Dutch'),
        ('Swedish'),
        ('None'),
        ('Japanese'),
        ('Latin'),
        ('Greek'),
        ('Yiddish'),
        ('Sign Languages'),
        ('Mandarin'),
        ('Czech'),
        ('Polynesian'),
        ('Cantonese'),
        ('Arabic'),
        ('Vietnamese'),
        ('Romanian'),
        ('Urdu'),
        ('Hindi'),
        ('Portuguese'),
        ('Chinese'),
        ('Mari'),
        ('Swahili'),
        ('Hawaiian'),
        ('Ukrainian'),
        ('Hebrew'),
        ('Sicilian'),
        ('Inuktitut'),
        ('American Sign Language'),
        ('Sioux'),
        ('Turkish'),
        ('Welsh'),
        ('Polish'),
        ('Marathi'),
        ('Finnish'),
        ('Norwegian'),
        ('Esperanto'),
        ('Tagalog'),
        ('Georgian'),
        ('Swiss German'),
        ('Latvian'),
        ('Serbian'),
        ('Indonesian'),
        ('Azerbaijani'),
        ('Scottish Gaelic'),
        ('Bable'),
        ('Nahuatl'),
        ('Flemish'),
        ('Maori'),
        ('Slovenian'),
        ('Catalan'),
        ('Afrikaans'),
        ('Serbo-Croatian'),
        ('Navajo'),
        ('North American Indian'),
        ('Telugu'),
        ('Tamil'),
        ('Bengali'),
        ('Korean'),
        ('Occitan'),
        ('Irish'),
        ('Athapascan languages'),
        ('Basque'),
        ('Albanian'),
        ('Bulgarian'),
        ('Quechua'),
        ('Greenlandic'),
        ('Burmese'),
        ('Thai'),
        ('Armenian'),
        ('Croatian'),
        ('Old'),
        ('Norse'),
        ('Macedonian'),
        ('Slovak'),
        ('Estonian'),
        ('Saami'),
        ('Ladino'),
        ('Indian Sign Language'),
        ('Scots'),
        ('Awadhi'),
        ('Arapaho'),
        ('Punjabi'),
        ('Romany'),
        ('Zulu'),
        ('Malayalam'),
        ('Sinhalese'),
        ('Malay'),
        ('Kirghiz'),
        ('Tatar'),
        ('Filipino'),
        ('Bhojpuri'),
        ('Aymara'),
        ('Mongolian'),
        ('Haitian'),
        ('Uzbek'),
        ('Persian'),
        ('Wolof'),
        ('Gujarati'),
        ('Ancient (to 1453)'),
        ('Konkani'),
        ('Apache languages'),
        ('Neapolitan'),
        ('Lithuanian'),
        ('Aboriginal'),
        ('Tupi'),
        ('Dyula'),
        ('Crow'),
        ('Kurdish'),
        ('Icelandic'),
        ('Breton'),
        ('Brazilian Sign Language'),
        ('Amharic'),
        ('Shona'),
        ('Sranan'),
        ('Kannada'),
        ('Sardinian'),
        ('Bambara'),
        ('French Sign Language'),
        ('Sindarin'),
        ('Maltese'),
        ('Samoan'),
        ('Klingon'),
        ('Ungwatsi'),
        ('Cheyenne'),
        ('Nepali'),
        ('Scanian'),
        ('More'),
        ('Sanskrit'),
        ('Berber languages'),
        ('Maya'),
        ('Min Nan'),
        ('Shanghainese'),
        ('Hakka'),
        ('Khmer'),
        ('Frisian'),
        ('Hokkien'),
        ('Tibetan'),
        ('Belarusian'),
        ('Guarani'),
        ('Peul'),
        ('Pushto'),
        ('Dari'),
        ('Assyrian Neo-Aramaic'),
        ('Hausa'),
        ('Ewe'),
        ('Spanish Sign Language'),
        ('Rajasthani'),
        ('Turkmen'),
        ('Southern Sotho'),
        ('Bosnian'),
        ('Lao'),
        ('Mandingo'),
        ('Pawnee'),
        ('Mohawk'),
        ('Algonquin'),
        ('Cree'),
        ('Hopi'),
        ('Kazakh'),
        ('Kriolu'),
        ('Tajik'),
        ('British Sign Language'),
        ('Akan'),
        ('Tigrigna'),
        ('Eastern Frisian'),
        ('Assamese'),
        ('Kabuverdianu'),
        ('Cornish'),
        ('Xhosa'),
        ('Egyptian (Ancient)'),
        ('Luxembourgish'),
        ('German Sign Language'),
        ('Chechen'),
        ('Mende'),
        ('Faroese'),
        ('Tamashek'),
        ('Syriac'),
        ('Tzotzil'),
        ('Kuna'),
        ('Tok Pisin'),
        ('Ojibwa'),
        ('Washoe'),
        ('Gallegan'),
        ('Shoshoni'),
        ('Russian Sign Language'),
        ('Papiamento'),
        ('Aramaic'),
        ('Old English'),
        ('Quenya'),
        ('Japanese Sign Language'),
        ('Malinka'),
        ('Lingala'),
        ('Nenets'),
        ('Tonga'),
        ('Visayan'),
        ('Yoruba'),
        ('Shanxi'),
        ('Somali'),
        ('Gumatj'),
        ('Ryukyuan'),
        ('Hassanya'),
        ('Corsican'),
        ('Korean Sign Language'),
        ('Mapudungun'),
        ('Dzongkha'),
        ('Nama'),
        ('Crimean Tatar'),
        ('Rotuman'),
        ('Kinyarwanda'),
        ('Kalmyk-Oirat'),
        ('Central American Indian languages'),
        ('Purepecha'),
        ('Teochew'),
        ('Uighur'),
        ('Kirundi'),
        ('Raeto-Romance'),
        ('Kabyle'),
        ('Tarahumara'),
        ('Low German'),
        ('Creek'),
        ('Kru'),
        ('Maithili'),
        ('Ladakhi'),
        ('Bicolano'),
        ('Yakut'),
        ('Nyanja'),
        ('Parsee'),
        ('Hmong'),
        ('Abkhazian'),
        ('Sindhi'),
        ('Tulu'),
        ('Acholi'),
        ('Ukrainian Sign Language'),
        ('Middle English'),
        ('Kashmiri'),
        ('Haryanvi'),
        ('Pular'),
        ('Kikuyu'),
        ('Ibo'),
        ('Fulah'),
        ('Micmac'),
        ('Montagnais'),
        ('Australian Sign Language'),
        ('Aromanian'),
        ('Aragonese'),
        ('Tswana'),
        ('Songhay'),
        ('Minangkabau'),
        ('Khanty'),
        ('Mirandese'),
        ('Himachali'),
        ('Oriya'),
        ('Dinka'),
        ('Manipuri'),
        ('Rhaetian'),
        ('Mixtec'),
        ('Bemba'),
        ('Wayuu'),
        ('Balinese'),
        ('Soninke'),
        ('Haida');
