insert into public.language (id, name)
values  (1, 'English'),
        (2, 'Italian'),
        (3, 'German'),
        (4, 'Danish'),
        (5, 'French'),
        (6, 'Hungarian'),
        (7, 'Russian'),
        (8, 'Spanish'),
        (9, 'Dutch'),
        (10, 'Swedish'),
        (11, 'None'),
        (12, 'Japanese'),
        (13, 'Latin'),
        (14, 'Greek'),
        (15, 'Yiddish'),
        (16, 'Sign Languages'),
        (17, 'Mandarin'),
        (18, 'Czech'),
        (19, 'Polynesian'),
        (20, 'Cantonese'),
        (21, 'Arabic'),
        (22, 'Vietnamese'),
        (23, 'Romanian'),
        (24, 'Urdu'),
        (25, 'Hindi'),
        (26, 'Portuguese'),
        (27, 'Chinese'),
        (28, 'Mari'),
        (29, 'Swahili'),
        (30, 'Hawaiian'),
        (31, 'Ukrainian'),
        (32, 'Hebrew'),
        (33, 'Sicilian'),
        (34, 'Inuktitut'),
        (35, 'American Sign Language'),
        (36, 'Sioux'),
        (37, 'Turkish'),
        (38, 'Welsh'),
        (39, 'Polish'),
        (40, 'Marathi'),
        (41, 'Finnish'),
        (42, 'Norwegian'),
        (43, 'Esperanto'),
        (44, 'Tagalog'),
        (45, 'Georgian'),
        (46, 'Swiss German'),
        (47, 'Latvian'),
        (48, 'Serbian'),
        (49, 'Indonesian'),
        (50, 'Azerbaijani'),
        (51, 'Scottish Gaelic'),
        (52, 'Bable'),
        (53, 'Nahuatl'),
        (54, 'Flemish'),
        (55, 'Maori'),
        (56, 'Slovenian'),
        (57, 'Catalan'),
        (58, 'Afrikaans'),
        (59, 'Serbo-Croatian'),
        (60, 'Navajo'),
        (61, 'North American Indian'),
        (62, 'Telugu'),
        (63, 'Tamil'),
        (64, 'Bengali'),
        (65, 'Korean'),
        (66, 'Occitan'),
        (67, 'Irish'),
        (68, 'Athapascan languages'),
        (69, 'Basque'),
        (70, 'Albanian'),
        (71, 'Bulgarian'),
        (72, 'Quechua'),
        (73, 'Greenlandic'),
        (74, 'Burmese'),
        (75, 'Thai'),
        (76, 'Armenian'),
        (77, 'Croatian'),
        (78, 'Old'),
        (79, 'Norse'),
        (80, 'Macedonian'),
        (81, 'Slovak'),
        (82, 'Estonian'),
        (83, 'Saami'),
        (84, 'Ladino'),
        (85, 'Indian Sign Language'),
        (86, 'Scots'),
        (87, 'Awadhi'),
        (88, 'Arapaho'),
        (89, 'Punjabi'),
        (90, 'Romany'),
        (91, 'Zulu'),
        (92, 'Malayalam'),
        (93, 'Sinhalese'),
        (94, 'Malay'),
        (95, 'Kirghiz'),
        (96, 'Tatar'),
        (97, 'Filipino'),
        (98, 'Bhojpuri'),
        (99, 'Aymara'),
        (100, 'Mongolian'),
        (101, 'Haitian'),
        (102, 'Uzbek'),
        (103, 'Persian'),
        (104, 'Wolof'),
        (105, 'Gujarati'),
        (106, 'Ancient (to 1453)'),
        (107, 'Konkani'),
        (108, 'Apache languages'),
        (109, 'Neapolitan'),
        (110, 'Lithuanian'),
        (111, 'Aboriginal'),
        (112, 'Tupi'),
        (113, 'Dyula'),
        (114, 'Crow'),
        (115, 'Kurdish'),
        (116, 'Icelandic'),
        (117, 'Breton'),
        (118, 'Brazilian Sign Language'),
        (119, 'Amharic'),
        (120, 'Shona'),
        (121, 'Sranan'),
        (122, 'Kannada'),
        (123, 'Sardinian'),
        (124, 'Bambara'),
        (125, 'French Sign Language'),
        (126, 'Sindarin'),
        (127, 'Maltese'),
        (128, 'Samoan'),
        (129, 'Klingon'),
        (130, 'Ungwatsi'),
        (131, 'Cheyenne'),
        (132, 'Nepali'),
        (133, 'Scanian'),
        (134, 'More'),
        (135, 'Sanskrit'),
        (136, 'Berber languages'),
        (137, 'Maya'),
        (138, 'Min Nan'),
        (139, 'Shanghainese'),
        (140, 'Hakka'),
        (141, 'Khmer'),
        (142, 'Frisian'),
        (143, 'Hokkien'),
        (144, 'Tibetan'),
        (145, 'Belarusian'),
        (146, 'Guarani'),
        (147, 'Peul'),
        (148, 'Pushto'),
        (149, 'Dari'),
        (150, 'Assyrian Neo-Aramaic'),
        (151, 'Hausa'),
        (152, 'Ewe'),
        (153, 'Spanish Sign Language'),
        (154, 'Rajasthani'),
        (155, 'Turkmen'),
        (156, 'Southern Sotho'),
        (157, 'Bosnian'),
        (158, 'Lao'),
        (159, 'Mandingo'),
        (160, 'Pawnee'),
        (161, 'Mohawk'),
        (162, 'Algonquin'),
        (163, 'Cree'),
        (164, 'Hopi'),
        (165, 'Kazakh'),
        (166, 'Kriolu'),
        (167, 'Tajik'),
        (168, 'British Sign Language'),
        (169, 'Akan'),
        (170, 'Tigrigna'),
        (171, 'Eastern Frisian'),
        (172, 'Assamese'),
        (173, 'Kabuverdianu'),
        (174, 'Cornish'),
        (175, 'Xhosa'),
        (176, 'Egyptian (Ancient)'),
        (177, 'Luxembourgish'),
        (178, 'German Sign Language'),
        (179, 'Chechen'),
        (180, 'Mende'),
        (181, 'Faroese'),
        (182, 'Tamashek'),
        (183, 'Syriac'),
        (184, 'Tzotzil'),
        (185, 'Kuna'),
        (186, 'Tok Pisin'),
        (187, 'Ojibwa'),
        (188, 'Washoe'),
        (189, 'Gallegan'),
        (190, 'Shoshoni'),
        (191, 'Russian Sign Language'),
        (192, 'Papiamento'),
        (193, 'Aramaic'),
        (194, 'Old English'),
        (195, 'Quenya'),
        (196, 'Japanese Sign Language'),
        (197, 'Malinka'),
        (198, 'Lingala'),
        (199, 'Nenets'),
        (200, 'Tonga'),
        (201, 'Visayan'),
        (202, 'Yoruba'),
        (203, 'Shanxi'),
        (204, 'Somali'),
        (205, 'Gumatj'),
        (206, 'Ryukyuan'),
        (207, 'Hassanya'),
        (208, 'Corsican'),
        (209, 'Korean Sign Language'),
        (210, 'Mapudungun'),
        (211, 'Dzongkha'),
        (212, 'Nama'),
        (213, 'Crimean Tatar'),
        (214, 'Rotuman'),
        (215, 'Kinyarwanda'),
        (216, 'Kalmyk-Oirat'),
        (217, 'Central American Indian languages'),
        (218, 'Purepecha'),
        (219, 'Teochew'),
        (220, 'Uighur'),
        (221, 'Kirundi'),
        (222, 'Raeto-Romance'),
        (223, 'Kabyle'),
        (224, 'Tarahumara'),
        (225, 'Low German'),
        (226, 'Creek'),
        (227, 'Kru'),
        (228, 'Maithili'),
        (229, 'Ladakhi'),
        (230, 'Bicolano'),
        (231, 'Yakut'),
        (232, 'Nyanja'),
        (233, 'Parsee'),
        (234, 'Hmong'),
        (235, 'Abkhazian'),
        (236, 'Sindhi'),
        (237, 'Tulu'),
        (238, 'Acholi'),
        (239, 'Ukrainian Sign Language'),
        (240, 'Middle English'),
        (241, 'Kashmiri'),
        (242, 'Haryanvi'),
        (243, 'Pular'),
        (244, 'Kikuyu'),
        (245, 'Ibo'),
        (246, 'Fulah'),
        (247, 'Micmac'),
        (248, 'Montagnais'),
        (249, 'Australian Sign Language'),
        (250, 'Aromanian'),
        (251, 'Aragonese'),
        (252, 'Tswana'),
        (253, 'Songhay'),
        (254, 'Minangkabau'),
        (255, 'Khanty'),
        (256, 'Mirandese'),
        (257, 'Himachali'),
        (258, 'Oriya'),
        (259, 'Dinka'),
        (260, 'Manipuri'),
        (261, 'Rhaetian'),
        (262, 'Mixtec'),
        (263, 'Bemba'),
        (264, 'Wayuu'),
        (265, 'Balinese'),
        (266, 'Soninke'),
        (267, 'Haida');
