insert into genre (name)
values ('Romance'),
       ('Crime'),
       ('Biography'),
       ('Drama'),
       ('History'),
       ('Fantasy'),
       ('Adventure'),
       ('War'),
       ('Mystery'),
       ('Horror'),
       ('Western'),
       ('Comedy'),
       ('Family'),
       ('Action'),
       ('Sci-Fi'),
       ('Thriller'),
       ('Sport'),
       ('Animation'),
       ('Musical'),
       ('Music'),
       ('Film-Noir'),
       ('Adult'),
       ('Documentary'),
       ('Reality-TV'),
       ('News');
