insert into public.genre (id, name)
values  (1, 'Romance'),
        (2, 'Crime'),
        (3, 'Biography'),
        (4, 'Drama'),
        (5, 'History'),
        (6, 'Fantasy'),
        (7, 'Adventure'),
        (8, 'War'),
        (9, 'Mystery'),
        (10, 'Horror'),
        (11, 'Western'),
        (12, 'Comedy'),
        (13, 'Family'),
        (14, 'Action'),
        (15, 'Sci-Fi'),
        (16, 'Thriller'),
        (17, 'Sport'),
        (18, 'Animation'),
        (19, 'Musical'),
        (20, 'Music'),
        (21, 'Film-Noir'),
        (22, 'Adult'),
        (23, 'Documentary'),
        (24, 'Reality-TV'),
        (25, 'News');
